name: Validate PR Title Format

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:

permissions:
  pull-requests: write

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: deepakputhraya/action-pr-title@3864bebc79c5f829d25dd42d3c6579d040b0ef16 # v1.0.2
        with:
          regex: 'IMX-\d+'
          prefix_case_sensitive: false
          min_length: 5
          max_length: 1000

      - name: Comment on PR if title check fails
        if: failure()
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;

            try {
              await github.rest.issues.createComment({
                ...repo,
                issue_number: prNumber,
                body: 'The PR title does not meet the required format. Please ensure it matches the pattern `IMX-\\d+` (e.g., `IMX-1234 Add new feature`).'
              });
            } catch (error) {
              core.setFailed(`Failed to comment on the PR: ${error.message}`);
            }
