name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: 'IMX-\d+'
          allowed_prefixes: ''
          disallowed_prefixes: ''
          prefix_case_sensitive: false
          min_length: 1
          max_length: 1000
